# runtime: python
runtime: python38
service: default

entrypoint: gunicorn -t 0 -b 0.0.0.0:8080 code.app:server

instance_class: F1

automatic_scaling:
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 30ms

resources:
    cpu: 1
    memory_gb: 1
    disk_size_gb: 10
