# runtime: python
runtime: python38
service: default

entrypoint: gunicorn -t 0 -b 0.0.0.0:8080 code.app:server

instance_class: F1

basic_scaling:
    max_instances: 1
    idle_timeout: 20m

resources:
    cpu: 1
    memory_gb: 1
    disk_size_gb: 10
